import Link from "next/link";
import { ArrowRight, CalendarDays, FileText, ImageIcon } from "lucide-react";
import { GenerationProgress } from "@/components/ai/generation-progress";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { prisma } from "@/lib/db";
import { requireWorkspaceBySlug } from "@/lib/utils/workspace";

export default async function CampaignDetailPage({ params }: { params: Promise<{ workspaceSlug: string; id: string }> }) {
  const { workspaceSlug, id } = await params;
  const { workspace } = await requireWorkspaceBySlug(workspaceSlug);
  const campaign = await prisma.campaign.findFirst({ where: { id, workspaceId: workspace.id }, include: { generatedPosts: true, campaignAssets: true, aiJobs: { orderBy: { createdAt: "desc" }, take: 6 } } });
  if (!campaign) return <div className="py-20 text-center text-slate-400">Campaign not found.</div>;
  return <section><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2"><Badge tone={campaign.status === "REVIEW" ? "amber" : campaign.status === "ACTIVE" ? "emerald" : "indigo"}>{campaign.status.replaceAll("_", " ")}</Badge><span className="text-xs text-slate-500">{campaign.goal.replaceAll("_", " ")}</span></div><h1 className="mt-3 text-3xl font-semibold tracking-tight text-white">{campaign.name}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">{campaign.description || "This campaign is ready for a sharper brief."}</p></div><div className="flex gap-2"><Link href={"/"+workspace.slug+"/campaigns/"+campaign.id+"/posts"} className="rounded-xl border border-white/10 px-4 py-2.5 text-sm text-slate-200 hover:bg-white/5">Review posts</Link><Link href={"/"+workspace.slug+"/campaigns/"+campaign.id+"/analytics"} className="rounded-xl border border-white/10 px-4 py-2.5 text-sm text-slate-200 hover:bg-white/5">Analytics</Link></div></div>
    <div className="mt-8"><GenerationProgress campaignId={campaign.id} /></div>
    <div className="mt-6 grid gap-5 xl:grid-cols-[1fr_.8fr]"><Card className="p-5"><div className="flex items-center justify-between"><h2 className="font-medium text-white">Agent activity</h2><span className="text-xs text-slate-500">{campaign.aiJobs.length} tracked jobs</span></div><div className="mt-5 space-y-4">{campaign.aiJobs.length ? campaign.aiJobs.map((job) => <div key={job.id} className="flex gap-3"><span className={job.status === "COMPLETED" ? "mt-1.5 size-2 rounded-full bg-emerald-300" : job.status === "FAILED" ? "mt-1.5 size-2 rounded-full bg-rose-300" : "mt-1.5 size-2 rounded-full bg-indigo-300"} /><div><p className="text-sm text-slate-200">{job.agentType.replaceAll("_", " ")}</p><p className="text-xs text-slate-500">{job.status.toLowerCase()} · {job.duration ? job.duration + "ms" : "waiting for work"}</p></div></div>) : <p className="text-sm text-slate-500">Generation will add an auditable activity trail here.</p>}</div></Card><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-1"><Card className="p-5"><FileText className="size-5 text-indigo-200" /><p className="mt-5 text-3xl font-semibold text-white">{campaign.generatedPosts.length}</p><p className="mt-1 text-sm text-slate-400">Generated posts ready to shape</p></Card><Card className="p-5"><ImageIcon className="size-5 text-cyan-200" /><p className="mt-5 text-3xl font-semibold text-white">{campaign.campaignAssets.length}</p><p className="mt-1 text-sm text-slate-400">Creative directions and scripts</p></Card></div></div>
    <Card className="mt-5 p-5"><div className="flex items-center gap-2"><CalendarDays className="size-4 text-slate-400" /><p className="font-medium text-white">Campaign cadence</p></div><p className="mt-2 text-sm leading-6 text-slate-400">Use the approval inbox as the publishing gate, then schedule posts in your workspace calendar. Every state change is retained in the audit log.</p><Link className="mt-4 inline-flex items-center gap-2 text-sm text-indigo-300" href={"/"+workspace.slug+"/calendar"}>Open calendar <ArrowRight className="size-4" /></Link></Card>
  </section>;
}
